/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/categories": {
    get: {
      responses: {
        /** @description OK */
        200: {
          content: {
            "application/json": components["schemas"]["Category"][];
          };
        };
      };
    };
    post: {
      requestBody: {
        content: {
          "application/json": components["schemas"]["Category"];
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: never;
        };
      };
    };
  };
  "/categories/{id}": {
    get: {
      parameters: {
        path: {
          id: number | string;
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: never;
        };
      };
    };
    put: {
      parameters: {
        path: {
          id: number | string;
        };
      };
      requestBody: {
        content: {
          "application/json": components["schemas"]["Category"];
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: never;
        };
      };
    };
    delete: {
      parameters: {
        path: {
          id: number | string;
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: never;
        };
      };
    };
  };
  "/categories/{id}/rules": {
    get: {
      parameters: {
        path: {
          id: number | string;
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: never;
        };
      };
    };
    post: {
      parameters: {
        path: {
          id: number | string;
        };
      };
      requestBody: {
        content: {
          "application/json": components["schemas"]["CategoryRule"];
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: never;
        };
      };
    };
  };
  "/categories/rules/{id}": {
    delete: {
      parameters: {
        path: {
          id: number | string;
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: never;
        };
      };
    };
  };
  "/transactions": {
    get: {
      parameters: {
        query: {
          pageNumber: number | string;
          from?: string;
          to?: string;
          categoryId?: number | string;
          search?: string;
          sortBy?: string;
          sortDir?: string;
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: never;
        };
      };
    };
  };
  "/transactions/{id}": {
    get: {
      parameters: {
        path: {
          id: string;
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: never;
        };
      };
    };
    put: {
      parameters: {
        path: {
          id: string;
        };
      };
      requestBody: {
        content: {
          "application/json": components["schemas"]["Transaction"];
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: never;
        };
      };
    };
    delete: {
      parameters: {
        path: {
          id: string;
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: never;
        };
      };
    };
  };
  "/import": {
    post: {
      requestBody: {
        content: {
          "multipart/form-data": {
            csv: components["schemas"]["IFormFile"];
          };
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: never;
        };
      };
    };
  };
  "/import/batches": {
    get: {
      responses: {
        /** @description OK */
        200: {
          content: never;
        };
      };
    };
  };
  "/import/batches/{id}": {
    delete: {
      parameters: {
        path: {
          id: string;
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: never;
        };
      };
    };
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    Category: {
      /** Format: int32 */
      id?: number | string;
      name: string;
      isDefault?: boolean;
      transactions?: components["schemas"]["Transaction"][];
      rules?: components["schemas"]["CategoryRule"][];
    };
    CategoryRule: {
      /** Format: int32 */
      id?: number | string;
      keyword: string;
      /** Format: int32 */
      categoryId?: number | string;
      category: components["schemas"]["Category"];
      source?: string;
      /** Format: date-time */
      createdAt?: string;
    };
    /** Format: binary */
    IFormFile: string;
    Transaction: {
      /** Format: int32 */
      id?: number | string;
      /** Format: date */
      date?: string;
      description: string;
      /** Format: double */
      amount?: number | string;
      /** Format: int32 */
      categoryId?: number | string;
      category?: null | components["schemas"]["Category"];
      accountSource?: string;
      /** Format: uuid */
      importBatchId?: string;
      rawLine?: null | string;
      /** Format: date-time */
      createdAt?: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export type operations = Record<string, never>;
