MERCHANT_RULES = {
    # Dagligvare
    "EXTRA": ("Extra", "Dagligvare"),
    "KIWI": ("Kiwi", "Dagligvare"),
    "REMA": ("Rema 1000", "Dagligvare"),
    "COOP": ("Coop", "Dagligvare"),
    "Bunnpris": ("Bunnpris", "Dagligvare"),
    "Spar Lena": ("Spar", "Dagligvare"),
    "Joker": ("Joker", "Dagligvare"),
    "Matkroken": ("Matkroken", "Dagligvare"),
    "Cc Mat": ("CC Mat", "Dagligvare"),
    "Mix Bilit": ("Mix", "Dagligvare"),
    "Vinmonopolet": ("Vinmonopolet", "Dagligvare"),
    "Obs Rudsh": ("Obs", "Dagligvare"),
    # Mat ute
    "Burger King": ("Burger King", "Mat ute"),
    "Mdc 048": ("McDonald's", "Mat ute"),
    "Mcdonalds": ("McDonald's", "Mat ute"),
    "BK 5079": ("Burger King", "Mat ute"),
    "Little Eat": ("Little Eat", "Mat ute"),
    "Fly Chicken": ("Fly Chicken", "Mat ute"),
    "Expressenpizza": ("Expressen Pizza", "Mat ute"),
    "Pizzabakeren": ("Pizzabakeren", "Mat ute"),
    "Raufoss Pizza": ("Raufoss Pizza", "Mat ute"),
    "Dos Amigos": ("Dos Amigos", "Mat ute"),
    "Sander Asia Mat": ("Sander Asia Mat", "Mat ute"),
    "Gelatiamo": ("Gelatiamo", "Mat ute"),
    "Thai Bahn": ("Thai Bahn", "Mat ute"),
    "Wolt": ("Wolt", "Mat ute"),
    "foodora": ("Foodora", "Mat ute"),
    "Cafe Amsterdam": ("Cafe Amsterdam", "Mat ute"),
    "Hygge Gjøvik": ("Hygge", "Mat ute"),
    "Kitch,n": ("Kitch'n", "Mat ute"),
    "Javel Oslo": ("Javel", "Mat ute"),
    "Totensnacks": ("Totensnacks", "Mat ute"),
    "King Kebap": ("King Kebap", "Mat ute"),
    "Selecta": ("Selecta", "Mat ute"),
    "Øya Maritim": ("Øya Maritim", "Mat ute"),
    "Max Burgers": ("Max Burgers", "Mat ute"),
    "Dominos Pizza": ("Domino's", "Mat ute"),
    "Nebbenes Kro": ("Nebbenes Kro", "Mat ute"),
    # Hjem
    "IKEA": ("IKEA", "Hjem"),
    "Søstrene Grene": ("Søstrene Grene", "Hjem"),
    "Biltema": ("Biltema", "Hjem"),
    "Rusta": ("Rusta", "Hjem"),
    "Jula": ("Jula", "Hjem"),
    "Clas Ohl": ("Clas Ohlson", "Hjem"),
    "Plantasjen": ("Plantasjen", "Hjem"),
    "Kid 47": ("Kid Interiør", "Hjem"),
    "Europris": ("Europris", "Hjem"),
    "Normal": ("Normal", "Hjem"),
    "Buddy": ("Buddy", "Hjem"),
    "Musti": ("Musti", "Hjem"),
    "Jysk": ("Jysk", "Hjem"),
    "Nille": ("Nille", "Hjem"),
    # Netthandel
    "CDON": ("CDON", "Netthandel"),
    "Maxgaming": ("MaxGaming", "Netthandel"),
    "Junkyard": ("Junkyard", "Netthandel"),
    "proshop": ("Proshop", "Netthandel"),
    "Helthjem": ("Helthjem", "Netthandel"),
    "Thomann": ("Thomann", "Netthandel"),
    "Power": ("Power", "Netthandel"),
    "Xxl": ("XXL", "Netthandel"),
    "Norli": ("Norli", "Netthandel"),
    "Zalando": ("Zalando", "Netthandel"),
    "Bubbleroom": ("Bubbleroom", "Netthandel"),
    "CHANGE Lingerie": ("Change", "Netthandel"),
    "LYKO": ("Lyko", "Netthandel"),
    # Gaming
    "Steam": ("Steam", "Gaming"),
    "discord": ("Discord", "Gaming"),
    "riotgamesl": ("Riot Games", "Gaming"),
    "jagex": ("Jagex", "Gaming"),
    "eneba": ("Eneba", "Gaming"),
    # Underholdning
    "Gjøvik Kino": ("Gjøvik Kino", "Underholdning"),
    "Norsk Tipping": ("Norsk Tipping", "Underholdning"),
    "Totenbadet": ("Totenbadet", "Underholdning"),
    "Fjellhallen": ("Fjellhallen", "Underholdning"),
    "Geekevents": ("Geekevents", "Underholdning"),
    "Sveve": ("Sveve", "Underholdning"),
    "Fun Padel": ("Fun Padel", "Underholdning"),
    "Padel-senter": ("Padel-senter", "Underholdning"),
    "Mjøsstranda": ("Mjøsstranda", "Underholdning"),
    "Tikkio": ("Tikkio", "Underholdning"),
    # Abonnement
    "APPLE.COM/BILL": ("Apple", "Abonnement"),
    "tidalmusica": ("Tidal", "Abonnement"),
    "Telenor": ("Telenor", "Abonnement"),
    "Google One": ("Google One", "Abonnement"),
    "splice": ("Splice", "Abonnement"),
    "Claude.ai": ("Claude", "Abonnement"),
    "Anthropic": ("Anthropic", "Abonnement"),
    "OpenAI": ("OpenAI", "Abonnement"),
    "Scrimba": ("Scrimba", "Abonnement"),
    "Real Debrid": ("Real-Debrid", "Abonnement"),
    "Suno": ("Suno", "Abonnement"),
    "elitehosting": ("Elitehosting", "Abonnement"),
    "agderposten": ("Agderposten", "Abonnement"),
    "Lyse Tele": ("Ice", "Abonnement"),
    "lennardigi": ("Lennar Digital", "Abonnement"),
    "native Ins": ("Native Instruments", "Abonnement"),
    "Netflix": ("Netflix", "Abonnement"),
    "Disney Plus": ("Disney+", "Abonnement"),
    "storytel": ("Storytel", "Abonnement"),
    # Bil
    "Shell": ("Shell", "Bil"),
    "Yx 7-Eleven": ("YX 7-Eleven", "Bil"),
    "7-eleven": ("7-Eleven", "Bil"),
    "Uno-x": ("Uno-X", "Bil"),
    "Esso": ("Esso", "Bil"),
    "ST1": ("ST1", "Bil"),
    "Tesla Inc": ("Tesla Lading", "Bil"),
    "IONITY": ("Ionity", "Bil"),
    "KOPLE": ("Kople", "Bil"),
    "Recharge": ("Recharge", "Bil"),
    "Easypark": ("EasyPark", "Bil"),
    "Apcoa": ("Apcoa Parking", "Bil"),
    "Asfinag": ("Asfinag", "Bil"),
    "NORDEA FINANS": ("Nordea Finans", "Bil"),
    "Fremtind Forsikring": ("Fremtind Forsikring", "Bil"),
    # Bolig
    "Nedbetaling": ("Nedbetaling lån", "Bolig"),
    # Boutgifter
    "Fortum": ("Fortum", "Boutgifter"),
    "Vestre Toten Kommune": ("Vestre Toten Kommune", "Boutgifter"),
    "Ringsaker Kommune": ("Ringsaker Kommune", "Boutgifter"),
    "Globalconnect": ("Globalconnect", "Boutgifter"),
    "Mova AS": ("Mova", "Boutgifter"),
    "VERISURE": ("Verisure", "Boutgifter"),
    "GJENSIDIGE": ("Gjensidige", "Boutgifter"),
    "AGRIA": ("Agria", "Boutgifter"),
    # Helse
    "Spesialistsenter": ("Moelv Spesialistsenter", "Helse"),
    "Apotek": ("Apotek 1", "Helse"),
    "Legevakt": ("Gjøvik Legevakt", "Helse"),
    "Helfo": ("Helfo", "Helse"),
    "Rtg.polikl": ("Røntgen Poliklinikk", "Helse"),
    "Vitus": ("Vitus Apotek", "Helse"),
    "Legesenter": ("Legesenter", "Helse"),
    "Oslo Storbylege": ("Oslo Storbylegevakt", "Helse"),
    # Kosmetikk
    "Cutters": ("Cutters", "Kosmetikk"),
    "Blivakker": ("BliVakker", "Kosmetikk"),
    "Nailster": ("Nailster", "Kosmetikk"),
    "nordicnails": ("Nordic Nails", "Kosmetikk"),
    "NORDICFEEL": ("NordicFeel", "Kosmetikk"),
    "KICKS": ("Kicks", "Kosmetikk"),
    "Rituals": ("Rituals", "Kosmetikk"),
    "Farmasiet": ("Farmasiet", "Kosmetikk"),
    "Feel Raufoss": ("Feel", "Kosmetikk"),
    # Kreditt
    "Klarna": ("Klarna", "Kreditt"),
    "Qliro": ("Qliro", "Kreditt"),
    "Credicare": ("Credicare", "Kreditt"),
    "Tfbank": ("TF Bank", "Kreditt"),
    "Riverty": ("Riverty", "Kreditt"),
    "ARVATO": ("Arvato", "Kreditt"),
    # Transport
    "Ruter": ("Ruter", "Transport"),
    "Entur": ("Entur", "Transport"),
    "Posten Norge": ("Posten", "Transport"),
    "Crown Seaways": ("DFDS", "Transport"),
    "VY App": ("Vy", "Transport"),
    # Overføring
    "Overføring Innland": ("Overføring", "Overføring"),
    "Overføring ": ("Overføring", "Overføring"),
    "Kontoregulering": ("Kontoregulering", "Overføring"),
    "Revolut": ("Revolut", "Overføring"),
    "Adyen": ("Adyen", "Overføring"),
    # Inntekt
    "Nav": ("NAV", "Inntekt"),
    "Skatteetaten": ("Skatteetaten", "Inntekt"),
    "Lønn": ("Lønn", "Inntekt"),
    "ZTL PAYMENT": ("ZTL Payment", "Inntekt"),
    "LENA OG CENTRUM": ("Lena og Centrum Trafikkskole", "Inntekt"),
    # Annet
    "Renter": ("Renter", "Annet"),
    "DNB Aksje": ("DNB", "Annet"),
    "Omkostninger": ("Omkostninger", "Annet"),
    "Verdipapir": ("Verdipapir", "Annet"),
    "Sport 1": ("Sport 1", "Annet"),
    "NOX PADEL": ("Nox Padel", "Annet"),
}

CATEGORIES = [
    "Dagligvare",
    "Mat ute",
    "Hjem",
    "Underholdning",
    "Gaming",
    "Abonnement",
    "Netthandel",
    "Helse",
    "Kosmetikk",
    "Kreditt",
    "Transport",
    "Bil",
    "Bolig",
    "Boutgifter",
    "Overføring",
    "Inntekt",
    "Annet",
]
