// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ExpensesApi.Migrations
{
    [DbContext(typeof(ExpensesDb))]
    [Migration("20260217180845_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.3");

            modelBuilder.Entity("Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 100,
                            IsDefault = true,
                            Name = "Dagligvare"
                        },
                        new
                        {
                            Id = 200,
                            IsDefault = true,
                            Name = "Mat ute"
                        },
                        new
                        {
                            Id = 300,
                            IsDefault = true,
                            Name = "Hjem"
                        },
                        new
                        {
                            Id = 400,
                            IsDefault = true,
                            Name = "Underholdning"
                        },
                        new
                        {
                            Id = 500,
                            IsDefault = true,
                            Name = "Gaming"
                        },
                        new
                        {
                            Id = 600,
                            IsDefault = true,
                            Name = "Abonnement"
                        },
                        new
                        {
                            Id = 700,
                            IsDefault = true,
                            Name = "Netthandel"
                        },
                        new
                        {
                            Id = 800,
                            IsDefault = true,
                            Name = "Helse"
                        },
                        new
                        {
                            Id = 900,
                            IsDefault = true,
                            Name = "Kosmetikk"
                        },
                        new
                        {
                            Id = 1000,
                            IsDefault = true,
                            Name = "Kreditt"
                        },
                        new
                        {
                            Id = 1100,
                            IsDefault = true,
                            Name = "Transport"
                        },
                        new
                        {
                            Id = 1200,
                            IsDefault = true,
                            Name = "Bil"
                        },
                        new
                        {
                            Id = 1300,
                            IsDefault = true,
                            Name = "Bolig"
                        },
                        new
                        {
                            Id = 1400,
                            IsDefault = true,
                            Name = "Boutgifter"
                        },
                        new
                        {
                            Id = 1500,
                            IsDefault = true,
                            Name = "Forsikring"
                        },
                        new
                        {
                            Id = 1600,
                            IsDefault = true,
                            Name = "Overføring"
                        },
                        new
                        {
                            Id = 1700,
                            IsDefault = true,
                            Name = "Inntekt"
                        },
                        new
                        {
                            Id = 1800,
                            IsDefault = true,
                            Name = "Annet"
                        });
                });

            modelBuilder.Entity("CategoryRule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Keyword")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("CategoryRules");

                    b.HasData(
                        new
                        {
                            Id = 101,
                            CategoryId = 100,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Keyword = "EXTRA",
                            Source = "seed"
                        },
                        new
                        {
                            Id = 102,
                            CategoryId = 100,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Keyword = "KIWI",
                            Source = "seed"
                        },
                        new
                        {
                            Id = 103,
                            CategoryId = 100,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Keyword = "REMA",
                            Source = "seed"
                        },
                        new
                        {
                            Id = 104,
                            CategoryId = 100,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Keyword = "COOP",
                            Source = "seed"
                        },
                        new
                        {
                            Id = 105,
                            CategoryId = 100,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Keyword = "Bunnpris",
                            Source = "seed"
                        },
                        new
                        {
                            Id = 106,
                            CategoryId = 100,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Keyword = "Spar Lena",
                            Source = "seed"
                        },
                        new
                        {
                            Id = 107,
                            CategoryId = 100,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Keyword = "Joker",
                            Source = "seed"
                        },
                        new
                        {
                            Id = 108,
                            CategoryId = 100,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Keyword = "Matkroken",
                            Source = "seed"
                        },
                        new
                        {
                            Id = 109,
                            CategoryId = 100,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Keyword = "Cc Mat",
                            Source = "seed"
                        },
                        new
                        {
                            Id = 110,
                            CategoryId = 100,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Keyword = "Mix Bilit",
                            Source = "seed"
                        },
                        new
                        {
                            Id = 111,
                            CategoryId = 100,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Keyword = "Vinmonopolet",
                            Source = "seed"
                        },
                        new
                        {
                            Id = 112,
                            CategoryId = 100,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Keyword = "Obs Rudsh",
                            Source = "seed"
                        },
                        new
                        {
                            Id = 201,
                            CategoryId = 200,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Keyword = "Burger King",
                            Source = "seed"
                        },
                        new
                        {
                            Id = 202,
                            CategoryId = 200,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Keyword = "Mdc 048",
                            Source = "seed"
                        },
                        new
                        {
                            Id = 203,
                            CategoryId = 200,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Keyword = "Mcdonalds",
                            Source = "seed"
                        },
                        new
                        {
                            Id = 204,
                            CategoryId = 200,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Keyword = "BK 5079",
                            Source = "seed"
                        },
                        new
                        {
                            Id = 205,
                            CategoryId = 200,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Keyword = "Little Eat",
                            Source = "seed"
                        },
                        new
                        {
                            Id = 206,
                            CategoryId = 200,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Keyword = "Fly Chicken",
                            Source = "seed"
                        },
                        new
                        {
                            Id = 207,
                            CategoryId = 200,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Keyword = "Expressenpizza",
                            Source = "seed"
                        },
                        new
                        {
                            Id = 208,
                            CategoryId = 200,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Keyword = "Pizzabakeren",
                            Source = "seed"
                        },
                        new
                        {
                            Id = 209,
                            CategoryId = 200,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Keyword = "Raufoss Pizza",
                            Source = "seed"
                        },
                        new
                        {
                            Id = 210,
                            CategoryId = 200,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Keyword = "Dos Amigos",
                            Source = "seed"
                        },
                        new
                        {
                            Id = 211,
                            CategoryId = 200,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Keyword = "Sander Asia Mat",
                            Source = "seed"
                        },
                        new
                        {
                            Id = 212,
                            CategoryId = 200,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Keyword = "Gelatiamo",
                            Source = "seed"
                        },
                        new
                        {
                            Id = 213,
                            CategoryId = 200,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Keyword = "Thai Bahn",
                            Source = "seed"
                        },
                        new
                        {
                            Id = 214,
                            CategoryId = 200,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Keyword = "Wolt",
                            Source = "seed"
                        },
                        new
                        {
                            Id = 215,
                            CategoryId = 200,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Keyword = "foodora",
                            Source = "seed"
                        },
                        new
                        {
                            Id = 216,
                            CategoryId = 200,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Keyword = "Cafe Amsterdam",
                            Source = "seed"
                        },
                        new
                        {
                            Id = 217,
                            CategoryId = 200,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Keyword = "Hygge Gjøvik",
                            Source = "seed"
                        },
                        new
                        {
                            Id = 218,
                            CategoryId = 200,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Keyword = "Kitch,n",
                            Source = "seed"
                        },
                        new
                        {
                            Id = 219,
                            CategoryId = 200,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Keyword = "Javel Oslo",
                            Source = "seed"
                        },
                        new
                        {
                            Id = 220,
                            CategoryId = 200,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Keyword = "Totensnacks",
                            Source = "seed"
                        },
                        new
                        {
                            Id = 221,
                            CategoryId = 200,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Keyword = "King Kebap",
                            Source = "seed"
                        },
                        new
                        {
                            Id = 222,
                            CategoryId = 200,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Keyword = "Selecta",
                            Source = "seed"
                        },
                        new
                        {
                            Id = 223,
                            CategoryId = 200,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Keyword = "Øya Maritim",
                            Source = "seed"
                        },
                        new
                        {
                            Id = 224,
                            CategoryId = 200,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Keyword = "Max Burgers",
                            Source = "seed"
                        },
                        new
                        {
                            Id = 225,
                            CategoryId = 200,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Keyword = "Dominos Pizza",
                            Source = "seed"
                        },
                        new
                        {
                            Id = 226,
                            CategoryId = 200,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Keyword = "Nebbenes Kro",
                            Source = "seed"
                        },
                        new
                        {
                            Id = 227,
                            CategoryId = 200,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Keyword = "Shell",
                            Source = "seed"
                        },
                        new
                        {
                            Id = 228,
                            CategoryId = 200,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Keyword = "7-eleven",
                            Source = "seed"
                        },
                        new
                        {
                            Id = 229,
                            CategoryId = 200,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Keyword = "Esso",
                            Source = "seed"
                        },
                        new
                        {
                            Id = 230,
                            CategoryId = 200,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Keyword = "ST1",
                            Source = "seed"
                        },
                        new
                        {
                            Id = 301,
                            CategoryId = 300,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Keyword = "IKEA",
                            Source = "seed"
                        },
                        new
                        {
                            Id = 302,
                            CategoryId = 300,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Keyword = "Søstrene Grene",
                            Source = "seed"
                        },
                        new
                        {
                            Id = 303,
                            CategoryId = 300,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Keyword = "Biltema",
                            Source = "seed"
                        },
                        new
                        {
                            Id = 304,
                            CategoryId = 300,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Keyword = "Rusta",
                            Source = "seed"
                        },
                        new
                        {
                            Id = 305,
                            CategoryId = 300,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Keyword = "Jula",
                            Source = "seed"
                        },
                        new
                        {
                            Id = 306,
                            CategoryId = 300,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Keyword = "Clas Ohl",
                            Source = "seed"
                        },
                        new
                        {
                            Id = 307,
                            CategoryId = 300,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Keyword = "Plantasjen",
                            Source = "seed"
                        },
                        new
                        {
                            Id = 308,
                            CategoryId = 300,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Keyword = "Kid 47",
                            Source = "seed"
                        },
                        new
                        {
                            Id = 309,
                            CategoryId = 300,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Keyword = "Europris",
                            Source = "seed"
                        },
                        new
                        {
                            Id = 310,
                            CategoryId = 300,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Keyword = "Normal",
                            Source = "seed"
                        },
                        new
                        {
                            Id = 311,
                            CategoryId = 300,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Keyword = "Buddy",
                            Source = "seed"
                        },
                        new
                        {
                            Id = 312,
                            CategoryId = 300,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Keyword = "Musti",
                            Source = "seed"
                        },
                        new
                        {
                            Id = 313,
                            CategoryId = 300,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Keyword = "Jysk",
                            Source = "seed"
                        },
                        new
                        {
                            Id = 314,
                            CategoryId = 300,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Keyword = "Nille",
                            Source = "seed"
                        },
                        new
                        {
                            Id = 315,
                            CategoryId = 300,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Keyword = "Sport 1",
                            Source = "seed"
                        },
                        new
                        {
                            Id = 401,
                            CategoryId = 400,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Keyword = "Gjøvik Kino",
                            Source = "seed"
                        },
                        new
                        {
                            Id = 402,
                            CategoryId = 400,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Keyword = "Norsk Tipping",
                            Source = "seed"
                        },
                        new
                        {
                            Id = 403,
                            CategoryId = 400,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Keyword = "Totenbadet",
                            Source = "seed"
                        },
                        new
                        {
                            Id = 404,
                            CategoryId = 400,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Keyword = "Fjellhallen",
                            Source = "seed"
                        },
                        new
                        {
                            Id = 405,
                            CategoryId = 400,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Keyword = "Geekevents",
                            Source = "seed"
                        },
                        new
                        {
                            Id = 406,
                            CategoryId = 400,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Keyword = "Sveve",
                            Source = "seed"
                        },
                        new
                        {
                            Id = 407,
                            CategoryId = 400,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Keyword = "Fun Padel",
                            Source = "seed"
                        },
                        new
                        {
                            Id = 408,
                            CategoryId = 400,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Keyword = "Padel-senter",
                            Source = "seed"
                        },
                        new
                        {
                            Id = 409,
                            CategoryId = 400,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Keyword = "Mjøsstranda",
                            Source = "seed"
                        },
                        new
                        {
                            Id = 410,
                            CategoryId = 400,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Keyword = "Tikkio",
                            Source = "seed"
                        },
                        new
                        {
                            Id = 501,
                            CategoryId = 500,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Keyword = "Steam",
                            Source = "seed"
                        },
                        new
                        {
                            Id = 502,
                            CategoryId = 500,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Keyword = "discord",
                            Source = "seed"
                        },
                        new
                        {
                            Id = 503,
                            CategoryId = 500,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Keyword = "riotgamesl",
                            Source = "seed"
                        },
                        new
                        {
                            Id = 504,
                            CategoryId = 500,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Keyword = "jagex",
                            Source = "seed"
                        },
                        new
                        {
                            Id = 505,
                            CategoryId = 500,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Keyword = "eneba",
                            Source = "seed"
                        },
                        new
                        {
                            Id = 601,
                            CategoryId = 600,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Keyword = "APPLE.COM/BILL",
                            Source = "seed"
                        },
                        new
                        {
                            Id = 602,
                            CategoryId = 600,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Keyword = "tidalmusica",
                            Source = "seed"
                        },
                        new
                        {
                            Id = 603,
                            CategoryId = 600,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Keyword = "Telenor",
                            Source = "seed"
                        },
                        new
                        {
                            Id = 604,
                            CategoryId = 600,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Keyword = "Google One",
                            Source = "seed"
                        },
                        new
                        {
                            Id = 605,
                            CategoryId = 600,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Keyword = "splice",
                            Source = "seed"
                        },
                        new
                        {
                            Id = 606,
                            CategoryId = 600,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Keyword = "Claude.ai",
                            Source = "seed"
                        },
                        new
                        {
                            Id = 607,
                            CategoryId = 600,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Keyword = "Anthropic",
                            Source = "seed"
                        },
                        new
                        {
                            Id = 608,
                            CategoryId = 600,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Keyword = "OpenAI",
                            Source = "seed"
                        },
                        new
                        {
                            Id = 609,
                            CategoryId = 600,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Keyword = "Scrimba",
                            Source = "seed"
                        },
                        new
                        {
                            Id = 610,
                            CategoryId = 600,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Keyword = "Real Debrid",
                            Source = "seed"
                        },
                        new
                        {
                            Id = 611,
                            CategoryId = 600,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Keyword = "Suno",
                            Source = "seed"
                        },
                        new
                        {
                            Id = 612,
                            CategoryId = 600,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Keyword = "elitehosting",
                            Source = "seed"
                        },
                        new
                        {
                            Id = 613,
                            CategoryId = 600,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Keyword = "agderposten",
                            Source = "seed"
                        },
                        new
                        {
                            Id = 614,
                            CategoryId = 600,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Keyword = "Lyse Tele",
                            Source = "seed"
                        },
                        new
                        {
                            Id = 615,
                            CategoryId = 600,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Keyword = "lennardigi",
                            Source = "seed"
                        },
                        new
                        {
                            Id = 616,
                            CategoryId = 600,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Keyword = "native Ins",
                            Source = "seed"
                        },
                        new
                        {
                            Id = 617,
                            CategoryId = 600,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Keyword = "Netflix",
                            Source = "seed"
                        },
                        new
                        {
                            Id = 618,
                            CategoryId = 600,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Keyword = "Disney Plus",
                            Source = "seed"
                        },
                        new
                        {
                            Id = 619,
                            CategoryId = 600,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Keyword = "storytel",
                            Source = "seed"
                        },
                        new
                        {
                            Id = 620,
                            CategoryId = 600,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Keyword = "Mova AS",
                            Source = "seed"
                        },
                        new
                        {
                            Id = 701,
                            CategoryId = 700,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Keyword = "CDON",
                            Source = "seed"
                        },
                        new
                        {
                            Id = 702,
                            CategoryId = 700,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Keyword = "Maxgaming",
                            Source = "seed"
                        },
                        new
                        {
                            Id = 703,
                            CategoryId = 700,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Keyword = "Junkyard",
                            Source = "seed"
                        },
                        new
                        {
                            Id = 704,
                            CategoryId = 700,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Keyword = "proshop",
                            Source = "seed"
                        },
                        new
                        {
                            Id = 705,
                            CategoryId = 700,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Keyword = "Helthjem",
                            Source = "seed"
                        },
                        new
                        {
                            Id = 706,
                            CategoryId = 700,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Keyword = "Thomann",
                            Source = "seed"
                        },
                        new
                        {
                            Id = 707,
                            CategoryId = 700,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Keyword = "Power",
                            Source = "seed"
                        },
                        new
                        {
                            Id = 708,
                            CategoryId = 700,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Keyword = "Xxl",
                            Source = "seed"
                        },
                        new
                        {
                            Id = 709,
                            CategoryId = 700,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Keyword = "Norli",
                            Source = "seed"
                        },
                        new
                        {
                            Id = 710,
                            CategoryId = 700,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Keyword = "NOX PADEL",
                            Source = "seed"
                        },
                        new
                        {
                            Id = 801,
                            CategoryId = 800,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Keyword = "Spesialistsenter",
                            Source = "seed"
                        },
                        new
                        {
                            Id = 802,
                            CategoryId = 800,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Keyword = "Apotek",
                            Source = "seed"
                        },
                        new
                        {
                            Id = 803,
                            CategoryId = 800,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Keyword = "Legevakt",
                            Source = "seed"
                        },
                        new
                        {
                            Id = 804,
                            CategoryId = 800,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Keyword = "Helfo",
                            Source = "seed"
                        },
                        new
                        {
                            Id = 805,
                            CategoryId = 800,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Keyword = "Rtg.polikl",
                            Source = "seed"
                        },
                        new
                        {
                            Id = 806,
                            CategoryId = 800,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Keyword = "Vitus",
                            Source = "seed"
                        },
                        new
                        {
                            Id = 807,
                            CategoryId = 800,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Keyword = "Legesenter",
                            Source = "seed"
                        },
                        new
                        {
                            Id = 808,
                            CategoryId = 800,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Keyword = "Oslo Storbylege",
                            Source = "seed"
                        },
                        new
                        {
                            Id = 809,
                            CategoryId = 800,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Keyword = "Farmasiet",
                            Source = "seed"
                        },
                        new
                        {
                            Id = 901,
                            CategoryId = 900,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Keyword = "Cutters",
                            Source = "seed"
                        },
                        new
                        {
                            Id = 902,
                            CategoryId = 900,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Keyword = "Blivakker",
                            Source = "seed"
                        },
                        new
                        {
                            Id = 903,
                            CategoryId = 900,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Keyword = "Nailster",
                            Source = "seed"
                        },
                        new
                        {
                            Id = 904,
                            CategoryId = 900,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Keyword = "nordicnails",
                            Source = "seed"
                        },
                        new
                        {
                            Id = 905,
                            CategoryId = 900,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Keyword = "NORDICFEEL",
                            Source = "seed"
                        },
                        new
                        {
                            Id = 906,
                            CategoryId = 900,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Keyword = "KICKS",
                            Source = "seed"
                        },
                        new
                        {
                            Id = 907,
                            CategoryId = 900,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Keyword = "Rituals",
                            Source = "seed"
                        },
                        new
                        {
                            Id = 908,
                            CategoryId = 900,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Keyword = "Feel Raufoss",
                            Source = "seed"
                        },
                        new
                        {
                            Id = 909,
                            CategoryId = 900,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Keyword = "Zalando",
                            Source = "seed"
                        },
                        new
                        {
                            Id = 910,
                            CategoryId = 900,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Keyword = "Bubbleroom",
                            Source = "seed"
                        },
                        new
                        {
                            Id = 911,
                            CategoryId = 900,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Keyword = "CHANGE Lingerie",
                            Source = "seed"
                        },
                        new
                        {
                            Id = 912,
                            CategoryId = 900,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Keyword = "LYKO",
                            Source = "seed"
                        },
                        new
                        {
                            Id = 1001,
                            CategoryId = 1000,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Keyword = "Klarna",
                            Source = "seed"
                        },
                        new
                        {
                            Id = 1002,
                            CategoryId = 1000,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Keyword = "Qliro",
                            Source = "seed"
                        },
                        new
                        {
                            Id = 1003,
                            CategoryId = 1000,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Keyword = "Credicare",
                            Source = "seed"
                        },
                        new
                        {
                            Id = 1004,
                            CategoryId = 1000,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Keyword = "Tfbank",
                            Source = "seed"
                        },
                        new
                        {
                            Id = 1005,
                            CategoryId = 1000,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Keyword = "Riverty",
                            Source = "seed"
                        },
                        new
                        {
                            Id = 1006,
                            CategoryId = 1000,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Keyword = "ARVATO",
                            Source = "seed"
                        },
                        new
                        {
                            Id = 1101,
                            CategoryId = 1100,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Keyword = "Ruter",
                            Source = "seed"
                        },
                        new
                        {
                            Id = 1102,
                            CategoryId = 1100,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Keyword = "Entur",
                            Source = "seed"
                        },
                        new
                        {
                            Id = 1103,
                            CategoryId = 1100,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Keyword = "Crown Seaways",
                            Source = "seed"
                        },
                        new
                        {
                            Id = 1104,
                            CategoryId = 1100,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Keyword = "VY App",
                            Source = "seed"
                        },
                        new
                        {
                            Id = 1105,
                            CategoryId = 1100,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Keyword = "Asfinag",
                            Source = "seed"
                        },
                        new
                        {
                            Id = 1201,
                            CategoryId = 1200,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Keyword = "Uno-x",
                            Source = "seed"
                        },
                        new
                        {
                            Id = 1202,
                            CategoryId = 1200,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Keyword = "Tesla Inc",
                            Source = "seed"
                        },
                        new
                        {
                            Id = 1203,
                            CategoryId = 1200,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Keyword = "IONITY",
                            Source = "seed"
                        },
                        new
                        {
                            Id = 1204,
                            CategoryId = 1200,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Keyword = "KOPLE",
                            Source = "seed"
                        },
                        new
                        {
                            Id = 1205,
                            CategoryId = 1200,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Keyword = "Recharge",
                            Source = "seed"
                        },
                        new
                        {
                            Id = 1206,
                            CategoryId = 1200,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Keyword = "Easypark",
                            Source = "seed"
                        },
                        new
                        {
                            Id = 1207,
                            CategoryId = 1200,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Keyword = "Apcoa",
                            Source = "seed"
                        },
                        new
                        {
                            Id = 1208,
                            CategoryId = 1200,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Keyword = "NORDEA FINANS",
                            Source = "seed"
                        },
                        new
                        {
                            Id = 1301,
                            CategoryId = 1300,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Keyword = "Nedbetaling",
                            Source = "seed"
                        },
                        new
                        {
                            Id = 1401,
                            CategoryId = 1400,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Keyword = "Fortum",
                            Source = "seed"
                        },
                        new
                        {
                            Id = 1402,
                            CategoryId = 1400,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Keyword = "Vestre Toten Kommune",
                            Source = "seed"
                        },
                        new
                        {
                            Id = 1403,
                            CategoryId = 1400,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Keyword = "Ringsaker Kommune",
                            Source = "seed"
                        },
                        new
                        {
                            Id = 1404,
                            CategoryId = 1400,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Keyword = "Globalconnect",
                            Source = "seed"
                        },
                        new
                        {
                            Id = 1405,
                            CategoryId = 1400,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Keyword = "VERISURE",
                            Source = "seed"
                        },
                        new
                        {
                            Id = 1501,
                            CategoryId = 1500,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Keyword = "Fremtind Forsikring",
                            Source = "seed"
                        },
                        new
                        {
                            Id = 1502,
                            CategoryId = 1500,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Keyword = "GJENSIDIGE",
                            Source = "seed"
                        },
                        new
                        {
                            Id = 1503,
                            CategoryId = 1500,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Keyword = "AGRIA",
                            Source = "seed"
                        },
                        new
                        {
                            Id = 1601,
                            CategoryId = 1600,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Keyword = "Overføring Innland",
                            Source = "seed"
                        },
                        new
                        {
                            Id = 1602,
                            CategoryId = 1600,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Keyword = "Overføring ",
                            Source = "seed"
                        },
                        new
                        {
                            Id = 1603,
                            CategoryId = 1600,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Keyword = "Kontoregulering",
                            Source = "seed"
                        },
                        new
                        {
                            Id = 1604,
                            CategoryId = 1600,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Keyword = "Revolut",
                            Source = "seed"
                        },
                        new
                        {
                            Id = 1605,
                            CategoryId = 1600,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Keyword = "Adyen",
                            Source = "seed"
                        },
                        new
                        {
                            Id = 1701,
                            CategoryId = 1700,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Keyword = "Nav",
                            Source = "seed"
                        },
                        new
                        {
                            Id = 1702,
                            CategoryId = 1700,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Keyword = "Skatteetaten",
                            Source = "seed"
                        },
                        new
                        {
                            Id = 1703,
                            CategoryId = 1700,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Keyword = "Lønn",
                            Source = "seed"
                        },
                        new
                        {
                            Id = 1704,
                            CategoryId = 1700,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Keyword = "ZTL PAYMENT",
                            Source = "seed"
                        },
                        new
                        {
                            Id = 1705,
                            CategoryId = 1700,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Keyword = "LENA OG CENTRUM",
                            Source = "seed"
                        },
                        new
                        {
                            Id = 1801,
                            CategoryId = 1800,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Keyword = "Posten Norge",
                            Source = "seed"
                        },
                        new
                        {
                            Id = 1802,
                            CategoryId = 1800,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Keyword = "Renter",
                            Source = "seed"
                        },
                        new
                        {
                            Id = 1803,
                            CategoryId = 1800,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Keyword = "DNB Aksje",
                            Source = "seed"
                        },
                        new
                        {
                            Id = 1804,
                            CategoryId = 1800,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Keyword = "Omkostninger",
                            Source = "seed"
                        },
                        new
                        {
                            Id = 1805,
                            CategoryId = 1800,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Keyword = "Verdipapir",
                            Source = "seed"
                        });
                });

            modelBuilder.Entity("Transaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AccountSource")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Amount")
                        .HasColumnType("TEXT");

                    b.Property<int>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ImportBatchId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RawLine")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("CategoryRule", b =>
                {
                    b.HasOne("Category", "Category")
                        .WithMany("Rules")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Transaction", b =>
                {
                    b.HasOne("Category", "Category")
                        .WithMany("Transactions")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Category", b =>
                {
                    b.Navigation("Rules");

                    b.Navigation("Transactions");
                });
#pragma warning restore 612, 618
        }
    }
}
